### PR TITLE
Got working Google Map on portfolio

### PR DESCRIPTION
**Pull request by sderacy**
I was having some issues with incorporating the API into my portfolio so while I was trying to debug it, I decided to do some cleaning in other parts of the code. I grouped the ID tags in my CSS file, fixed some typos in the HTML, and made my redirect link go to the HTML page within the portfolio as opposed to my live app. 

I also had been having a weird issue where my random greeting servlet was removed from my portfolio, so I added it back in this PR. Because of this, I've held off on merging the other PR since that branch is set to merge with main. Hopefully, this PR helps resolves some of the issues but it also says it can't automatically merge so I guess we'll see.

### CODE REVIEW

**Comment by sderacy** [comment]
Just wanted to follow up - the conflict seemed to be that I had one more space in the newer version than the other, but other than that there were no other conflicts!

**Comment by papakoj** [comment]
Thanks for cleaning up your code and leaving a descriptive comment on this PR. It's very helpful!

**Review by papakoj — APPROVED** [review]
Looks good!

**Comment by sderacy** [comment]
No problem :) and thank you!

**Pull request merged**
