### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sderacy**
Updated the README.md file

### CODE REVIEW

**Review by alisonberkowitz — APPROVED** [review]
Just noticed you have an open PR, not sure if you wanted me to review this, but approving anyways just in case 😄

**Comment by sderacy** [comment]
Thanks for approving! I believe I made a mistake and merged the commits I just made with the commits that were approved a while back. Do you want me to revert the pull request so you and papakoj can properly review it?

**Comment by alisonberkowitz** [comment]
Ah yea, I just took a look and its okay for now, no worries!

In the future I'll wait until you have explicitly assigned me the PR to review before approving to try to avoid any confusion :)

**Comment by sderacy** [comment]
Oh awesome, thank you and sorry about that!

**Pull request merged**
